#!/bin/sh

set -e

# Data and stack limits for the whole build, including the freshly built
# interpreter that freezes the importlib modules.  PKG_PYTHON_DATA_LIMIT (in KB)
# overrides the data limit if the build runs out of memory.
ulimit -d ${PKG_PYTHON_DATA_LIMIT-65536}
ulimit -s 8192

DESTDIR=$1
VERSION=$2
PREFIX=/usr/local
PATCHFILE="python-$VERSION-openstep.patch"

PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC=/usr/local/bin/gcc-4.2
# -O3 works on x86.  On SPARC the freshly built interpreter fails while running
# the frozen importlib ("name 'RuntimeError' is not defined" although the name
# exists), which looks like a miscompile of the dictionary or string code by
# gcc 4.2, so SPARC builds more conservatively.  PKG_PYTHON_OPT overrides it.
case $PKG_ARCH in
    sparc) python_opt='-O1 -fno-strict-aliasing -fwrapv' ;;
    *)     python_opt=-O3 ;;
esac
python_opt=${PKG_PYTHON_OPT-$python_opt}
CFLAGS="$PKG_GCC42_ARCH_FLAGS $python_opt -DNeXT"
# GCC42 exhausts memory or crashes optimizing the generated deepfreeze unit.
# Keep the interpreter optimized; only frozen-object initialization uses -O0.
DEEPFREEZE_CFLAGS="-O0 -g0"
CPPFLAGS="-I. -I./Include -I/usr/local/include -I/NextDeveloper/Headers -I/NextDeveloper/Headers/bsd"
LDFLAGS="-L/usr/local/lib"
GREP=/usr/local/bin/grep
EGREP="/usr/local/bin/grep -E"
AWK=/usr/local/bin/gawk
SED=/bin/sed
ac_cv_prog_cc_c99=
ac_cv_sizeof_wchar_t=4

export DESTDIR VERSION PREFIX PATCHFILE PATH CC CFLAGS CPPFLAGS LDFLAGS
export DEEPFREEZE_CFLAGS
export GREP EGREP AWK SED ac_cv_prog_cc_c99 ac_cv_sizeof_wchar_t
. "$PKG_BUILD_HELPERS"

# OPENSTEP's SPARC libc compares bytes as signed in memcmp() and strcmp(); see
# pkg_cmp_shim in build-helpers.sh.  Empty on x86.  It is forced in at make
# time only: configure's own tests do not cope with it.
CMPFLAGS=`pkg_cmp_shim "\`pwd\`/openstep-cmp"`

if [ -d "Python-$VERSION" ]; then
    cd "Python-$VERSION"
    PATCHFILE="../$PATCHFILE"
fi

patch -p1 < "$PATCHFILE"

cat > Modules/Setup.local <<'EOF'
*static*

array arraymodule.c
_asyncio _asynciomodule.c
_bisect _bisectmodule.c
_contextvars _contextvarsmodule.c
_csv _csv.c
_heapq _heapqmodule.c
_json _json.c
_lsprof _lsprof.c rotatingtree.c
_opcode _opcode.c
_pickle _pickle.c
_queue _queuemodule.c
_random _randommodule.c
_struct _struct.c
_typing _typingmodule.c
_zoneinfo _zoneinfo.c

audioop audioop.c
math mathmodule.c
cmath cmathmodule.c
_statistics _statisticsmodule.c
_datetime _datetimemodule.c
_decimal _decimal/_decimal.c

binascii binascii.c
zlib zlibmodule.c

_md5 md5module.c
_sha1 sha1module.c
_sha256 sha256module.c
_sha512 sha512module.c
_sha3 _sha3/sha3module.c
_blake2 _blake2/blake2module.c _blake2/blake2b_impl.c _blake2/blake2s_impl.c

pyexpat pyexpat.c
_elementtree _elementtree.c

_codecs_cn cjkcodecs/_codecs_cn.c
_codecs_hk cjkcodecs/_codecs_hk.c
_codecs_iso2022 cjkcodecs/_codecs_iso2022.c
_codecs_jp cjkcodecs/_codecs_jp.c
_codecs_kr cjkcodecs/_codecs_kr.c
_codecs_tw cjkcodecs/_codecs_tw.c
_multibytecodec cjkcodecs/multibytecodec.c
unicodedata unicodedata.c

fcntl fcntlmodule.c
grp grpmodule.c
_posixsubprocess _posixsubprocess.c
select selectmodule.c
_socket socketmodule.c
EOF

run_configure --build=$PKG_TARGET --host=$PKG_TARGET \
  --prefix="$PREFIX" --disable-shared --without-ensurepip \
  --disable-test-modules

gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS" SHELL=/usr/local/bin/ksh
gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS" SHELL=/usr/local/bin/ksh install DESTDIR="$DESTDIR"
