#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin
CC=/usr/local/bin/gcc-4.2
CFLAGS="$PKG_GCC42_ARCH_FLAGS "'-O2 -DNeXT -D_POSIX_SOURCE -D_NEXT_SOURCE'
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
AWK=/usr/local/bin/gawk
export PATH CC CFLAGS GREP EGREP AWK
if test -d "lha-$VERSION"; then cd "lha-$VERSION"; fi
. "$PKG_BUILD_HELPERS"

# Upstream security fixes ported by hand to this p1 release (see the patch
# header): huf.c read_c_len zero-run bound (CVE-2006-4338), level 0/1/2/3
# header length and negative-size checks (CVE-2016-1925), get_bytes overflow,
# no extracting through symlinks, no symlinks from `lha p', checked seek/getc.
pkg_apply_patch "lha-$VERSION-cve.patch"

run_configure --prefix=/usr/local --build=$PKG_TARGET --host=$PKG_TARGET \
    --disable-dependency-tracking
/bin/gnumake
/bin/gnumake install DESTDIR="$DESTDIR"
