#!/bin/sh

set -e

TMP=/usr/tmp/libsvgtiny-test.$$

cat > "$TMP.c" <<'EOF'
#include <string.h>
#include <svgtiny.h>

int
main(void)
{
    const char *svg =
        "<svg xmlns=\"http://www.w3.org/2000/svg\" "
        "width=\"10\" height=\"10\"></svg>";
    struct svgtiny_diagram *diagram;
    svgtiny_code code;

    diagram = svgtiny_create();
    if (diagram == 0)
        return 1;

    code = svgtiny_parse(diagram, svg, strlen(svg), "", 10, 10);
    svgtiny_free(diagram);

    return code == svgtiny_OK ? 0 : 2;
}
EOF

/usr/local/bin/gcc -DNeXT -I"$LOCAL_ROOT/include" "$TMP.c" \
    "$LOCAL_ROOT/lib/libsvgtiny.a" "$LOCAL_ROOT/lib/libdom.a" \
    "$LOCAL_ROOT/lib/libhubbub.a" "$LOCAL_ROOT/lib/libparserutils.a" \
    "$LOCAL_ROOT/lib/libwapcaplet.a" "$LOCAL_ROOT/lib/libexpat.a" \
    -lm -o "$TMP"

"$TMP"

rm -f "$TMP.c" "$TMP"
