#!/bin/sh
set -e
TMP=/usr/tmp/gcrypt-test.$$
trap '/bin/rm -f "$TMP" "$TMP.c"' 0
trap 'exit 1' 1 2 15
cat > "$TMP.c" <<'EOF'
#include <gcrypt.h>
#include <assert.h>
#include <string.h>
int main(void)
{
    static const unsigned char sha256[32] = {
        0xba,0x78,0x16,0xbf,0x8f,0x01,0xcf,0xea,0x41,0x41,0x40,0xde,0x5d,0xae,0x22,0x23,
        0xb0,0x03,0x61,0xa3,0x96,0x17,0x7a,0x9c,0xb4,0x10,0xff,0x61,0xf2,0x00,0x15,0xad };
    static const unsigned char cipher[16] = {
        0x69,0xc4,0xe0,0xd8,0x6a,0x7b,0x04,0x30,0xd8,0xcd,0xb7,0x80,0x70,0xb4,0xc5,0x5a };
    static const unsigned char wrapped[24] = {
        0x1f,0xa6,0x8b,0x0a,0x81,0x12,0xb4,0x47,0xae,0xf3,0x4b,0xd8,
        0xfb,0x5a,0x7b,0x82,0x9d,0x3e,0x86,0x23,0x71,0xd2,0xcf,0xe5 };
    unsigned char wrap_output[24];
    unsigned char digest[32], key[16], plain[16], encrypted[16], decrypted[16];
    gcry_cipher_hd_t handle;
    int i;
    assert(gcry_check_version(GCRYPT_VERSION));
    assert(!gcry_control(GCRYCTL_DISABLE_SECMEM, 0));
    assert(!gcry_control(GCRYCTL_INITIALIZATION_FINISHED, 0));
    gcry_md_hash_buffer(GCRY_MD_SHA256, digest, "abc", 3);
    assert(!memcmp(digest, sha256, sizeof digest));
    for (i=0; i<16; ++i) { key[i]=i; plain[i]=17*i; }
    assert(!gcry_cipher_open(&handle, GCRY_CIPHER_AES128, GCRY_CIPHER_MODE_ECB, 0));
    assert(!gcry_cipher_setkey(handle, key, sizeof key));
    assert(!gcry_cipher_encrypt(handle, encrypted, sizeof encrypted, plain, sizeof plain));
    assert(!memcmp(encrypted, cipher, sizeof cipher));
    assert(!gcry_cipher_decrypt(handle, decrypted, sizeof decrypted, encrypted, sizeof encrypted));
    assert(!memcmp(decrypted, plain, sizeof plain));
    gcry_cipher_close(handle);
    assert(!gcry_cipher_open(&handle, GCRY_CIPHER_AES128, GCRY_CIPHER_MODE_AESWRAP, 0));
    assert(!gcry_cipher_setkey(handle, key, sizeof key));
    assert(!gcry_cipher_encrypt(handle, wrap_output, sizeof wrap_output, plain, sizeof plain));
    assert(!memcmp(wrap_output, wrapped, sizeof wrapped));
    gcry_cipher_close(handle);
    return 0;
}
EOF
/usr/local/bin/gcc-4.2 -O2 ${PKG_GCC42_ARCH_FLAGS-} -DNeXT -Wno-deprecated-declarations \
    `"$LOCAL_ROOT/bin/libgcrypt-config" --cflags` "$TMP.c" \
    `"$LOCAL_ROOT/bin/libgcrypt-config" --libs` -o "$TMP"
"$TMP"
"$LOCAL_ROOT/bin/dumpsexp" --version
echo 'libgcrypt installed headers, SHA-256, AES and AES key-wrap vectors passed'
