#!/bin/sh

set -e

TMPDIR=/tmp/expat-test-$$

test -f "$LOCAL_ROOT/include/expat.h"
test -f "$LOCAL_ROOT/include/expat_external.h"
test -f "$LOCAL_ROOT/include/expat_openstep.h"
test -f "$LOCAL_ROOT/lib/libexpat.a"

mkdir "$TMPDIR"
trap 'rm -rf "$TMPDIR"' 0 1 2 3 15

echo '#include <expat.h>' > "$TMPDIR/conftest.c"
echo 'int main(){XML_Parser p=XML_ParserCreate(0); if(p==0) return 1; XML_ParserFree(p); return 0;}' >> "$TMPDIR/conftest.c"

/usr/local/bin/gcc -DNeXT -I"$LOCAL_ROOT/include" "$TMPDIR/conftest.c" \
  "$LOCAL_ROOT/lib/libexpat.a" -o "$TMPDIR/conftest"
"$TMPDIR/conftest"
