#!/bin/sh
set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:$PATH
CC=/usr/local/bin/gcc-4.2
CFLAGS="$PKG_GCC42_ARCH_FLAGS "'-g -O2 -std=gnu99'
CPPFLAGS='-D_POSIX_SOURCE -I/usr/local/include/ncurses -I/usr/local/include -I/NextDeveloper/Headers/bsd'
LDFLAGS=-L/usr/local/lib
GREP=/usr/local/bin/grep
EGREP=/usr/local/bin/egrep
AWK=/usr/local/bin/gawk
SED=/bin/sed
PKG_CONFIG=false
CONFIG_SHELL=/usr/local/bin/ksh
# OPENSTEP frexp(infinity) loops forever; use the bundled replacement.
gl_cv_func_frexp_works=no
# The header exists, but the functions do not; use BSD ncurses handling.
ac_cv_header_termios_h=no
export PATH CC CFLAGS CPPFLAGS LDFLAGS GREP EGREP AWK SED PKG_CONFIG CONFIG_SHELL
export gl_cv_func_frexp_works ac_cv_header_termios_h
. "$PKG_BUILD_HELPERS"

patch -p1 < "nano-$VERSION-openstep.patch"
run_configure --prefix=/usr/local --build=$PKG_TARGET --host=$PKG_TARGET --disable-nls --disable-utf8 --disable-dependency-tracking

# Texinfo 4.8 does not understand the newer -c HEADERS=0 spelling.
/bin/gnumake AM_MAKEINFOHTMLFLAGS='--no-split --no-headers'
/bin/gnumake install DESTDIR="$DESTDIR" \
    AM_MAKEINFOHTMLFLAGS='--no-split --no-headers'
