#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
export DESTDIR VERSION PATH

if [ -d "lua-$VERSION" ]; then
    cd "lua-$VERSION"
fi

patch -p1 < "lua-$VERSION-openstep.patch"

(
    cd src
    /bin/gnumake all CC='/usr/local/bin/gcc-4.2 -std=gnu99'" $PKG_GCC42_ARCH_FLAGS" \
        AR='/bin/ar rcu' RANLIB=/bin/ranlib
    ./lua -v
    ./luac -v
)

# Stock mkdir has no -p; create the staging hierarchy in parent-first order.
for dir in usr usr/local usr/local/bin usr/local/include usr/local/lib \
    usr/local/man usr/local/man/man1 usr/local/share usr/local/share/lua \
    usr/local/share/lua/5.5 usr/local/lib/lua usr/local/lib/lua/5.5 \
    usr/local/share/doc usr/local/share/doc/lua
do
    test -d "$DESTDIR/$dir" || mkdir "$DESTDIR/$dir"
done

/bin/gnumake install INSTALL_TOP="$DESTDIR/usr/local" \
    MKDIR=: INSTALL_EXEC='cp -p' INSTALL_DATA='cp -p'
/bin/ranlib "$DESTDIR/usr/local/lib/liblua.a"
cp doc/*.html doc/*.css doc/*.png "$DESTDIR/usr/local/share/doc/lua/"
chmod 755 "$DESTDIR/usr/local/bin/lua" "$DESTDIR/usr/local/bin/luac"
