#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin
CC=/usr/local/bin/gcc-4.2
# COMPAT lets melt read freeze-1.0 archives.  Makefile.in's own CFLAGS is -I.
CFLAGS="-I. $PKG_GCC42_ARCH_FLAGS "'-O2 -DNeXT -DCOMPAT=1'
export PATH CC
if test -d "freeze-$VERSION"; then cd "freeze-$VERSION"; fi
patch -p1 < "freeze-$VERSION-openstep.patch"
# Hand-written configure that ignores almost every option; give it a shell.
"${CONFIG_SHELL-/usr/local/bin/ksh}" ./configure --prefix=/usr/local
/bin/gnumake prog CC="$CC" CFLAGS="$CFLAGS"
/usr/local/bin/mkdir -p "$DESTDIR/usr/local/bin" "$DESTDIR/usr/local/man/man1"
/bin/gnumake install DESTDIR="$DESTDIR" CC="$CC" CFLAGS="$CFLAGS"
