#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PREFIX=/usr/local
PATCHFILE="libnslog-$VERSION-openstep.patch"
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
NSSHARED=/usr/local/share/netsurf-buildsystem
CC="/usr/local/bin/gcc-4.2 $PKG_GCC42_ARCH_FLAGS"
BUILD_CC=/usr/local/bin/gcc-4.2
MAKE=gnumake
BISON=/usr/local/bin/bison
FLEX=/usr/local/bin/flex
CCACHE=
PKGCONFIG=
CC_CAN_BUILD_AND_DEP=no
CC_CANNOT_DEP=yes
INSTALL=/usr/bin/install
INSTALLFLAGS=-c
BUILDDIR=build-openstep

export DESTDIR VERSION PREFIX PATH NSSHARED CC BUILD_CC MAKE BISON FLEX
export CCACHE PKGCONFIG CC_CAN_BUILD_AND_DEP CC_CANNOT_DEP
export INSTALL INSTALLFLAGS BUILDDIR

if [ -d "libnslog-$VERSION" ]; then
    cd "libnslog-$VERSION"
    PATCHFILE="../$PATCHFILE"
fi

patch -p1 < "$PATCHFILE"

cat > Makefile.config <<'EOF'
CFLAGS := $(CFLAGS) -DNeXT
EOF

gnumake Q= PREFIX="$PREFIX" WARNFLAGS=
/bin/ranlib "$BUILDDIR/libnslog.a"

gnumake Q= install DESTDIR="$DESTDIR" PREFIX="$PREFIX" WARNFLAGS=
/bin/ranlib "$DESTDIR$PREFIX/lib/libnslog.a"
