#!/bin/sh

set -e

TMP=/usr/tmp/libdom-test.$$

cat > "$TMP.c" <<'EOF'
#include <dom/dom.h>

int main(void)
{
    dom_document *doc = 0;
    dom_exception err;

    err = dom_implementation_create_document(
        DOM_IMPLEMENTATION_CORE, 0, 0, 0, 0, 0, &doc);
    if (err != DOM_NO_ERR || doc == 0)
        return 1;

    dom_node_unref(doc);
    return 0;
}
EOF

/usr/local/bin/gcc -DNeXT -I/NextDeveloper/Headers -I"$LOCAL_ROOT/include" "$TMP.c" \
    "$LOCAL_ROOT/lib/libdom.a" "$LOCAL_ROOT/lib/libhubbub.a" \
    "$LOCAL_ROOT/lib/libparserutils.a" "$LOCAL_ROOT/lib/libwapcaplet.a" -o "$TMP"

"$TMP"

rm -f "$TMP.c" "$TMP"
