#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PREFIX=/usr/local
PATCHFILE="libnsutils-$VERSION-openstep.patch"
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
NSSHARED=/usr/local/share/netsurf-buildsystem
CC=cc
BUILD_CC=cc
MAKE=gnumake
CCACHE=
PKGCONFIG=
INSTALL=/usr/bin/install
INSTALLFLAGS=-c
BUILDDIR=build-openstep

export DESTDIR VERSION PREFIX PATH NSSHARED CC BUILD_CC MAKE
export CCACHE PKGCONFIG INSTALL INSTALLFLAGS BUILDDIR

if [ -d "libnsutils-$VERSION" ]; then
    cd "libnsutils-$VERSION"
    PATCHFILE="../$PATCHFILE"
fi

patch -p1 < "$PATCHFILE"

cat > Makefile.config <<'EOF'
CFLAGS := $(CFLAGS) -DNeXT
EOF

gnumake Q= PREFIX="$PREFIX" WARNFLAGS=
/bin/ranlib "$BUILDDIR/libnsutils.a"

gnumake Q= install DESTDIR="$DESTDIR" PREFIX="$PREFIX" WARNFLAGS=
/bin/ranlib "$DESTDIR$PREFIX/lib/libnsutils.a"
