#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PREFIX=/usr/local
PATCHFILE="libnsbmp-$VERSION-openstep.patch"
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
NSSHARED=/usr/local/share/netsurf-buildsystem
CC=/usr/local/bin/gcc
BUILD_CC=/usr/local/bin/gcc
MAKE=gnumake
CCACHE=
PKGCONFIG=
CC_CAN_BUILD_AND_DEP=no
CC_CANNOT_DEP=yes
INSTALL=/usr/bin/install
INSTALLFLAGS=-c

export DESTDIR VERSION PREFIX PATH NSSHARED CC BUILD_CC MAKE
export CCACHE PKGCONFIG CC_CAN_BUILD_AND_DEP CC_CANNOT_DEP
export INSTALL INSTALLFLAGS

if [ -d "libnsbmp-$VERSION" ]; then
    cd "libnsbmp-$VERSION"
    PATCHFILE="../$PATCHFILE"
fi

patch -p1 < "$PATCHFILE"

gnumake Q= PREFIX="$PREFIX" WARNFLAGS=

for lib in build-*-release-lib-static/libnsbmp.a; do
    test -f "$lib" || continue
    /bin/ranlib "$lib"
done

gnumake Q= install DESTDIR="$DESTDIR" PREFIX="$PREFIX" WARNFLAGS=

if [ -f "$DESTDIR$PREFIX/lib/libnsbmp.a" ]; then
    /bin/ranlib "$DESTDIR$PREFIX/lib/libnsbmp.a"
fi
