#!/bin/sh

set -e

TMP=/usr/tmp/libnsbmp-test.$$

cat > "$TMP.c" <<'EOF'
#include <stdlib.h>
#include <string.h>
#include <libnsbmp.h>

static void *create(int width, int height, unsigned int state)
{
    (void) state;
    return malloc(width * height * 4);
}

static void destroy(void *bitmap)
{
    free(bitmap);
}

static unsigned char *buffer(void *bitmap)
{
    return bitmap;
}

int main(void)
{
    bmp_bitmap_callback_vt callbacks;
    bmp_image bmp;

    memset(&callbacks, 0, sizeof(callbacks));
    callbacks.bitmap_create = create;
    callbacks.bitmap_destroy = destroy;
    callbacks.bitmap_get_buffer = buffer;

    bmp_create(&bmp, &callbacks);
    bmp_finalise(&bmp);
    return 0;
}
EOF

/usr/local/bin/gcc -DNeXT -I"$LOCAL_ROOT/include" "$TMP.c" \
    "$LOCAL_ROOT/lib/libnsbmp.a" -o "$TMP"

"$TMP"

rm -f "$TMP.c" "$TMP"
