#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
. "$PKG_BUILD_HELPERS"
PATH=/usr/ucb:/bin:/usr/bin
CC="/bin/cc -traditional-cpp $PKG_SYSCC_ARCH_FLAGS"
CFLAGS='-O0'
CPPFLAGS='-I/usr/local/include'
LDFLAGS='-L/usr/local/lib'
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
AWK=/usr/local/bin/gawk
SED=/bin/sed
PKG_CONFIG=/bin/false
am_cv_func_iconv=no
am_cv_lib_iconv=no
export am_cv_func_iconv am_cv_lib_iconv
# The function works on OPENSTEP but its BSD headers omit the declaration.
ac_cv_have_decl_getdtablesize=yes
export ac_cv_have_decl_getdtablesize
CONFIG_SHELL=/usr/local/bin/ksh
export PATH CC CFLAGS CPPFLAGS LDFLAGS GREP EGREP AWK SED PKG_CONFIG CONFIG_SHELL
/usr/local/bin/patch -p1 < "wget-$VERSION-openstep.patch"
run_configure --build=$PKG_TARGET --host=$PKG_TARGET \
  --prefix=/usr/local --with-ssl=openssl \
  --with-libssl-prefix=/usr/local --without-libpsl --without-zlib \
  --without-metalink --without-cares --without-libuuid --disable-iri \
  --disable-pcre --disable-nls --disable-ipv6 --disable-ntlm --disable-opie \
  --disable-xattr --disable-dependency-tracking
# Both the generated configure files and their inputs carry the port fixes.
# SPARC libc's memcmp()/strcmp() compare bytes as signed.  This gnulib will not
# take a forced -include (pkg_cmp_shim), so link in unsigned definitions (see
# pkg_cmp_obj); they are added at make time only.
CMPOBJ=`pkg_cmp_obj "\`pwd\`/openstep-cmp"`
/bin/gnumake ACLOCAL=true AUTOCONF=true AUTOHEADER=true AUTOMAKE=true LDFLAGS="$LDFLAGS $CMPOBJ"
for dir in "$DESTDIR/usr" "$DESTDIR/usr/local" "$DESTDIR/usr/local/bin"; do
    test -d "$dir" || /bin/mkdir "$dir"
done
/usr/bin/install -c -m 755 src/wget "$DESTDIR/usr/local/bin/wget-bootstrap"
