#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
PATCHFILE="openssl-$VERSION-openstep.patch"
SRCDIR="openssl-$VERSION"

export DESTDIR VERSION PATH

if [ -d "$SRCDIR" ]; then
    cd "$SRCDIR"
fi

patch -p1 < "$PATCHFILE"
/bin/gnumake
/bin/gnumake install_sw DESTDIR="$DESTDIR"

test -d "$DESTDIR/usr" || mkdir "$DESTDIR/usr"
test -d "$DESTDIR/usr/local" || mkdir "$DESTDIR/usr/local"
test -d "$DESTDIR/usr/local/ssl" || mkdir "$DESTDIR/usr/local/ssl"
test -d "$DESTDIR/usr/local/ssl/certs" || mkdir "$DESTDIR/usr/local/ssl/certs"
test -d "$DESTDIR/usr/local/ssl/private" || mkdir "$DESTDIR/usr/local/ssl/private"
test -d "$DESTDIR/usr/local/ssl/misc" || mkdir "$DESTDIR/usr/local/ssl/misc"
