#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
case "$DESTDIR" in
//*) DESTDIR="/`echo "$DESTDIR" | sed 's#^/*##'`" ;;
esac
ROOTDIR=`pwd`
BOOTSTRAP_VERSION=2.95.3
BOOTSTRAP_SRC="$ROOTDIR/bootstrap/gcc-$BOOTSTRAP_VERSION"
BOOTSTRAP_PREFIX="$ROOTDIR/bootstrap-root/usr/local"
BOOTSTRAP_PATCH="$BOOTSTRAP_SRC/gcc-$BOOTSTRAP_VERSION.next.patch"
BOOTSTRAP_SPECSFILE="$ROOTDIR/specs.gcc295"
GCC3_SRC="$ROOTDIR/gcc-gcc-1640"
GCC3_VERSION=3.3
PATCHFILE="$GCC3_SRC/gcc-1640.next.patch"
SPECSFILE="$GCC3_SRC/specs.gcc33"
BUILD_SUBDIR="$GCC3_SRC/build-openstep"
PATH=/usr/local/bin:/bin:/usr/bin
CONFIG_SHELL=/usr/local/bin/ksh
MAKEINFO=/usr/local/bin/makeinfo
FLEX=/usr/local/bin/flex
HOST_ALIAS=i386-next-openstep4
BOOTSTRAP_TARGET=i386-next-nextstep4
TARGET="$HOST_ALIAS"
FINAL_PREFIX=/usr/local
STAGE_PREFIX="$DESTDIR$FINAL_PREFIX"
SPECS_DIR="$STAGE_PREFIX/lib/gcc-lib/$TARGET/$GCC3_VERSION"
GXX_INCLUDE_DIR="$STAGE_PREFIX/include/c++/$GCC3_VERSION"
GXX_BITS_DIR="$GXX_INCLUDE_DIR/bits"
GCC3_CFLAGS='-g -O0'
LIBSTDCXX_SUBDIRS='include libio libmath libsupc++ src po'

export DESTDIR VERSION ROOTDIR BOOTSTRAP_VERSION BOOTSTRAP_SRC BOOTSTRAP_PREFIX
export BOOTSTRAP_PATCH BOOTSTRAP_SPECSFILE GCC3_SRC GCC3_VERSION PATCHFILE SPECSFILE BUILD_SUBDIR
export PATH CONFIG_SHELL MAKEINFO FLEX HOST_ALIAS BOOTSTRAP_TARGET TARGET FINAL_PREFIX STAGE_PREFIX SPECS_DIR
export GXX_INCLUDE_DIR GXX_BITS_DIR
export GCC3_CFLAGS LIBSTDCXX_SUBDIRS

cd "$BOOTSTRAP_SRC"
patch -p1 < "$BOOTSTRAP_PATCH"
CC=cc
export CC
"$CONFIG_SHELL" ./configure --prefix="$BOOTSTRAP_PREFIX" --enable-languages=c,c++,objc --disable-shared
/bin/gnumake

test -d "$ROOTDIR/bootstrap-root" || mkdir "$ROOTDIR/bootstrap-root"
test -d "$ROOTDIR/bootstrap-root/usr" || mkdir "$ROOTDIR/bootstrap-root/usr"
test -d "$BOOTSTRAP_PREFIX" || mkdir "$BOOTSTRAP_PREFIX"
test -d "$BOOTSTRAP_PREFIX/bin" || mkdir "$BOOTSTRAP_PREFIX/bin"
test -d "$BOOTSTRAP_PREFIX/include" || mkdir "$BOOTSTRAP_PREFIX/include"
test -d "$BOOTSTRAP_PREFIX/info" || mkdir "$BOOTSTRAP_PREFIX/info"
test -d "$BOOTSTRAP_PREFIX/lib" || mkdir "$BOOTSTRAP_PREFIX/lib"
test -d "$BOOTSTRAP_PREFIX/lib/gcc-lib" || mkdir "$BOOTSTRAP_PREFIX/lib/gcc-lib"
test -d "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET" || mkdir "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET"
test -d "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION" || mkdir "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION"
test -d "$BOOTSTRAP_PREFIX/man" || mkdir "$BOOTSTRAP_PREFIX/man"
test -d "$BOOTSTRAP_PREFIX/man/man1" || mkdir "$BOOTSTRAP_PREFIX/man/man1"
test -d "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET" || mkdir "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET"
test -d "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/bin" || mkdir "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/bin"
test -d "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/include" || mkdir "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/include"

/bin/gnumake install \
    prefix="$BOOTSTRAP_PREFIX" \
    exec_prefix="$BOOTSTRAP_PREFIX" \
    bindir="$BOOTSTRAP_PREFIX/bin" \
    libdir="$BOOTSTRAP_PREFIX/lib" \
    libsubdir="$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION" \
    local_prefix="$BOOTSTRAP_PREFIX" \
    includedir="$BOOTSTRAP_PREFIX/include" \
    gcc_tooldir="$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET" \
    tooldir="$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET" \
    assertdir="$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/include" \
    infodir="$BOOTSTRAP_PREFIX/info" \
    mandir="$BOOTSTRAP_PREFIX/man" \
    man1dir="$BOOTSTRAP_PREFIX/man/man1"

/bin/cp "$BOOTSTRAP_SPECSFILE" \
    "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION/specs"

PATH="$BOOTSTRAP_PREFIX/bin:/usr/local/bin:/bin:/usr/bin"
CC="$BOOTSTRAP_PREFIX/bin/gcc"
CXX="$BOOTSTRAP_PREFIX/bin/g++"
export PATH CC CXX

cd "$GCC3_SRC"
patch -p1 < "$PATCHFILE"
sed 's/#inst\.\$\$#/inst.\$\$/g' install-sh > install-sh.new
mv install-sh.new install-sh

test -d "$BUILD_SUBDIR" || mkdir "$BUILD_SUBDIR"
cd "$BUILD_SUBDIR"

FLEX="$FLEX" "$CONFIG_SHELL" ../configure --build="$HOST_ALIAS" --host="$HOST_ALIAS" --prefix="$FINAL_PREFIX" --enable-languages=c,c++,objc --disable-shared
if [ -f ../gcc/gengtype-lex.c ]; then
    /bin/cp ../gcc/gengtype-lex.c gcc/gengtype-lex.c
fi
/bin/gnumake CFLAGS="$GCC3_CFLAGS" FLEX="$FLEX" all-gcc

BUILD_GCC_INCLUDE_DIR="$BUILD_SUBDIR/gcc/include"
test -d "$BUILD_GCC_INCLUDE_DIR/architecture" || mkdir "$BUILD_GCC_INCLUDE_DIR/architecture"
cat > "$BUILD_GCC_INCLUDE_DIR/architecture/ARCH_INCLUDE.h" <<'EOF'
#ifndef _ARCH_INCLUDE_H_
#define _ARCH_INCLUDE_H_

#define ARCH_INCLUDE(prefix, suffix) <prefix __next_i386__/suffix>

#endif
EOF

for header_i386_dir in /NextDeveloper/Headers/*/i386; do
    if [ -d "$header_i386_dir" ]; then
        header_family=`echo "$header_i386_dir" | sed 's#^/NextDeveloper/Headers/##; s#/i386$##'`
        test -d "$BUILD_GCC_INCLUDE_DIR/$header_family" || mkdir "$BUILD_GCC_INCLUDE_DIR/$header_family"
        test -d "$BUILD_GCC_INCLUDE_DIR/$header_family/__next_i386__" || mkdir "$BUILD_GCC_INCLUDE_DIR/$header_family/__next_i386__"
        (
            cd "$header_i386_dir"
            for staged_header in *.h; do
                /bin/rm -f "$BUILD_GCC_INCLUDE_DIR/$header_family/__next_i386__/$staged_header"
                /bin/cp "$staged_header" "$BUILD_GCC_INCLUDE_DIR/$header_family/__next_i386__/"
            done
        )
    fi
done

/bin/gnumake CFLAGS="$GCC3_CFLAGS" CXXFLAGS="$GCC3_CFLAGS" FLEX="$FLEX" SUBDIRS="$LIBSTDCXX_SUBDIRS" all-target-libstdc++-v3

test -d "$DESTDIR/usr" || mkdir "$DESTDIR/usr"
test -d "$DESTDIR/usr/local" || mkdir "$DESTDIR/usr/local"
test -d "$STAGE_PREFIX" || mkdir "$STAGE_PREFIX"
test -d "$STAGE_PREFIX/bin" || mkdir "$STAGE_PREFIX/bin"
test -d "$STAGE_PREFIX/include" || mkdir "$STAGE_PREFIX/include"
test -d "$STAGE_PREFIX/info" || mkdir "$STAGE_PREFIX/info"
test -d "$STAGE_PREFIX/lib" || mkdir "$STAGE_PREFIX/lib"
test -d "$STAGE_PREFIX/lib/gcc-lib" || mkdir "$STAGE_PREFIX/lib/gcc-lib"
test -d "$STAGE_PREFIX/lib/gcc-lib/$TARGET" || mkdir "$STAGE_PREFIX/lib/gcc-lib/$TARGET"
test -d "$STAGE_PREFIX/lib/gcc-lib/$TARGET/$GCC3_VERSION" || mkdir "$STAGE_PREFIX/lib/gcc-lib/$TARGET/$GCC3_VERSION"
test -d "$STAGE_PREFIX/man" || mkdir "$STAGE_PREFIX/man"
test -d "$STAGE_PREFIX/man/man1" || mkdir "$STAGE_PREFIX/man/man1"
test -d "$STAGE_PREFIX/man/man7" || mkdir "$STAGE_PREFIX/man/man7"
test -d "$STAGE_PREFIX/$TARGET" || mkdir "$STAGE_PREFIX/$TARGET"
test -d "$STAGE_PREFIX/$TARGET/bin" || mkdir "$STAGE_PREFIX/$TARGET/bin"
test -d "$STAGE_PREFIX/$TARGET/include" || mkdir "$STAGE_PREFIX/$TARGET/include"

/bin/gnumake DESTDIR= CFLAGS="$GCC3_CFLAGS" FLEX="$FLEX" install-gcc \
    prefix="$STAGE_PREFIX" \
    exec_prefix="$STAGE_PREFIX" \
    bindir="$STAGE_PREFIX/bin" \
    libdir="$STAGE_PREFIX/lib" \
    libsubdir="$STAGE_PREFIX/lib/gcc-lib/$TARGET/$GCC3_VERSION" \
    local_prefix="$STAGE_PREFIX" \
    includedir="$STAGE_PREFIX/include" \
    gcc_tooldir="$STAGE_PREFIX/$TARGET" \
    tooldir="$STAGE_PREFIX/$TARGET" \
    assertdir="$STAGE_PREFIX/$TARGET/include" \
    infodir="$STAGE_PREFIX/info" \
    mandir="$STAGE_PREFIX/man" \
    man1dir="$STAGE_PREFIX/man/man1"

/bin/gnumake DESTDIR= CFLAGS="$GCC3_CFLAGS" CXXFLAGS="$GCC3_CFLAGS" FLEX="$FLEX" SUBDIRS="$LIBSTDCXX_SUBDIRS" install-target-libstdc++-v3 \
    prefix="$STAGE_PREFIX" \
    exec_prefix="$STAGE_PREFIX" \
    bindir="$STAGE_PREFIX/bin" \
    libdir="$STAGE_PREFIX/lib" \
    includedir="$STAGE_PREFIX/include" \
    gcc_tooldir="$STAGE_PREFIX/$TARGET" \
    tooldir="$STAGE_PREFIX/$TARGET" \
    infodir="$STAGE_PREFIX/info" \
    mandir="$STAGE_PREFIX/man"

LIBSTDCXX_A="$STAGE_PREFIX/lib/libstdc++.a"
LIBSUPCXX_A="$STAGE_PREFIX/lib/libsupc++.a"
LIBSTDCXX_MERGE_DIR="$BUILD_SUBDIR/next-libstdcxx-merge"
if [ -f "$LIBSTDCXX_A" ] && [ -f "$LIBSUPCXX_A" ]; then
    /bin/rm -rf "$LIBSTDCXX_MERGE_DIR"
    mkdir "$LIBSTDCXX_MERGE_DIR"
    (
        cd "$LIBSTDCXX_MERGE_DIR"
        /bin/ar x "$LIBSUPCXX_A"
        /bin/rm -f __.SYMDEF*
        /bin/ar r "$LIBSTDCXX_A" *
        /bin/ranlib "$LIBSTDCXX_A"
    )
fi

test -d "$GXX_BITS_DIR" || mkdir "$GXX_BITS_DIR"
for target_bits_dir in "$GXX_INCLUDE_DIR/$TARGET/bits" "$BUILD_SUBDIR/$TARGET/libstdc++-v3/include/$TARGET/bits"; do
    if [ -d "$target_bits_dir" ]; then
        for target_header in atomicity.h basic_file.h c++config.h c++io.h c++locale.h codecvt_specializations.h ctype_base.h ctype_inline.h ctype_noninline.h gthr.h gthr-default.h gthr-posix.h gthr-single.h messages_members.h os_defines.h time_members.h; do
            if [ -f "$target_bits_dir/$target_header" ]; then
                /bin/rm -f "$GXX_BITS_DIR/$target_header"
                /bin/cp "$target_bits_dir/$target_header" "$GXX_BITS_DIR/$target_header"
            fi
        done
    fi
done

/bin/rm -f "$SPECS_DIR/specs"

test -d "$SPECS_DIR/include/architecture" || mkdir "$SPECS_DIR/include/architecture"
cat > "$SPECS_DIR/include/architecture/ARCH_INCLUDE.h" <<'EOF'
#ifndef _ARCH_INCLUDE_H_
#define _ARCH_INCLUDE_H_

/*
 * GNU cpp 3.3 does not accept OPENSTEP's original string-literal
 * ARCH_INCLUDE expansion in #include directives.  This target is i386-only,
 * so expand to an angle-bracket header name that cpplib can consume.
 * Do not use the literal i386 token here; Foundation expects i386 to be
 * defined as a macro, and macro expansion also happens in #include names.
 */
#define ARCH_INCLUDE(prefix, suffix) <prefix __next_i386__/suffix>

#endif
EOF

for header_i386_dir in /NextDeveloper/Headers/*/i386; do
    if [ -d "$header_i386_dir" ]; then
        header_family=`echo "$header_i386_dir" | sed 's#^/NextDeveloper/Headers/##; s#/i386$##'`
        test -d "$SPECS_DIR/include/$header_family" || mkdir "$SPECS_DIR/include/$header_family"
        test -d "$SPECS_DIR/include/$header_family/__next_i386__" || mkdir "$SPECS_DIR/include/$header_family/__next_i386__"
        (
            cd "$header_i386_dir"
            for staged_header in *.h; do
                /bin/rm -f "$SPECS_DIR/include/$header_family/__next_i386__/$staged_header"
                /bin/cp "$staged_header" "$SPECS_DIR/include/$header_family/__next_i386__/"
            done
        )
    fi
done
