#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:$PATH
PATCHFILE="gcc-$VERSION.next.patch"
SPECSPATCH="gcc.$VERSION.i386.specs.patch"
SPECSPATCHDIR="$DESTDIR/usr/local/share/gcc"
CONFIG_SHELL=/usr/local/bin/ksh
TARGET=i386-next-nextstep4
FINAL_PREFIX=/usr/local
STAGE_PREFIX="$DESTDIR$FINAL_PREFIX"

export DESTDIR VERSION PATH CONFIG_SHELL TARGET FINAL_PREFIX STAGE_PREFIX

patch -p1 < "$PATCHFILE"
"$CONFIG_SHELL" ./configure --prefix="$FINAL_PREFIX" --enable-languages=c,c++,objc --disable-shared
PATH=/bin:/usr/bin:/usr/local/bin
export PATH
/bin/gnumake
/bin/gnumake install \
    prefix="$STAGE_PREFIX" \
    exec_prefix="$STAGE_PREFIX" \
    bindir="$STAGE_PREFIX/bin" \
    libdir="$STAGE_PREFIX/lib" \
    libsubdir="$STAGE_PREFIX/lib/gcc-lib/$TARGET/$VERSION" \
    local_prefix="$STAGE_PREFIX" \
    includedir="$STAGE_PREFIX/include" \
    gcc_tooldir="$STAGE_PREFIX/$TARGET" \
    tooldir="$STAGE_PREFIX/$TARGET" \
    assertdir="$STAGE_PREFIX/$TARGET/include" \
    infodir="$STAGE_PREFIX/info" \
    mandir="$STAGE_PREFIX/man" \
    man1dir="$STAGE_PREFIX/man/man1"

test -d "$DESTDIR/usr" || mkdir "$DESTDIR/usr"
test -d "$DESTDIR/usr/local" || mkdir "$DESTDIR/usr/local"
test -d "$DESTDIR/usr/local/share" || mkdir "$DESTDIR/usr/local/share"
test -d "$SPECSPATCHDIR" || mkdir "$SPECSPATCHDIR"
cp "$SPECSPATCH" "$SPECSPATCHDIR/$SPECSPATCH"
