#!/bin/sh

set -e

PATH=/usr/local/bin:$PATH
PATCHFILE="$ROOT_DIR/usr/local/share/gcc/gcc.$PKG_VERSION.i386.specs.patch"
SPECSDIR="$ROOT_DIR/usr/local/lib/gcc-lib/i386-next-nextstep4/$PKG_VERSION"

export PATH PATCHFILE SPECSDIR

if [ -f "$PATCHFILE" ] && [ -d "$SPECSDIR" ]; then
    cd "$SPECSDIR"
    patch -p0 < "$PATCHFILE"
fi
