#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
case "$DESTDIR" in
//*) DESTDIR="/`echo "$DESTDIR" | sed 's#^/*##'`" ;;
esac
ROOTDIR=`pwd`
BOOTSTRAP_VERSION=2.95.3
BOOTSTRAP_SRC="$ROOTDIR/bootstrap/gcc-$BOOTSTRAP_VERSION"
BOOTSTRAP_PREFIX="$ROOTDIR/bootstrap-root/usr/local"
BOOTSTRAP_PATCH="$BOOTSTRAP_SRC/gcc-$BOOTSTRAP_VERSION.next.patch"
BOOTSTRAP_SPECSFILE="$ROOTDIR/specs.gcc295"
GCC3_SRC="$ROOTDIR/gcc-$VERSION"
PATCHFILE="$GCC3_SRC/gcc-$VERSION.next.patch"
SPECSFILE="$GCC3_SRC/specs.gcc3"
BUILD_SUBDIR="$GCC3_SRC/build-openstep"
PATH=/usr/local/bin:/bin:/usr/bin
CONFIG_SHELL=/usr/local/bin/ksh
MAKEINFO=/usr/local/bin/makeinfo
HOST_ALIAS=i386-next-openstep4
BOOTSTRAP_TARGET=i386-next-nextstep4
TARGET="$HOST_ALIAS"
FINAL_PREFIX=/usr/local
STAGE_PREFIX="$DESTDIR$FINAL_PREFIX"
SPECS_DIR="$STAGE_PREFIX/lib/gcc-lib/$TARGET/$VERSION"
GCC3_CFLAGS='-g -O0'

export DESTDIR VERSION ROOTDIR BOOTSTRAP_VERSION BOOTSTRAP_SRC BOOTSTRAP_PREFIX
export BOOTSTRAP_PATCH BOOTSTRAP_SPECSFILE GCC3_SRC PATCHFILE SPECSFILE BUILD_SUBDIR
export PATH CONFIG_SHELL MAKEINFO HOST_ALIAS BOOTSTRAP_TARGET TARGET FINAL_PREFIX STAGE_PREFIX SPECS_DIR
export GCC3_CFLAGS

cd "$BOOTSTRAP_SRC"
patch -p1 < "$BOOTSTRAP_PATCH"
CC=cc
export CC
"$CONFIG_SHELL" ./configure --prefix="$BOOTSTRAP_PREFIX" --enable-languages=c,c++,objc --disable-shared
/bin/gnumake

test -d "$ROOTDIR/bootstrap-root" || mkdir "$ROOTDIR/bootstrap-root"
test -d "$ROOTDIR/bootstrap-root/usr" || mkdir "$ROOTDIR/bootstrap-root/usr"
test -d "$BOOTSTRAP_PREFIX" || mkdir "$BOOTSTRAP_PREFIX"
test -d "$BOOTSTRAP_PREFIX/bin" || mkdir "$BOOTSTRAP_PREFIX/bin"
test -d "$BOOTSTRAP_PREFIX/include" || mkdir "$BOOTSTRAP_PREFIX/include"
test -d "$BOOTSTRAP_PREFIX/info" || mkdir "$BOOTSTRAP_PREFIX/info"
test -d "$BOOTSTRAP_PREFIX/lib" || mkdir "$BOOTSTRAP_PREFIX/lib"
test -d "$BOOTSTRAP_PREFIX/lib/gcc-lib" || mkdir "$BOOTSTRAP_PREFIX/lib/gcc-lib"
test -d "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET" || mkdir "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET"
test -d "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION" || mkdir "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION"
test -d "$BOOTSTRAP_PREFIX/man" || mkdir "$BOOTSTRAP_PREFIX/man"
test -d "$BOOTSTRAP_PREFIX/man/man1" || mkdir "$BOOTSTRAP_PREFIX/man/man1"
test -d "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET" || mkdir "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET"
test -d "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/bin" || mkdir "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/bin"
test -d "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/include" || mkdir "$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/include"

/bin/gnumake install \
    prefix="$BOOTSTRAP_PREFIX" \
    exec_prefix="$BOOTSTRAP_PREFIX" \
    bindir="$BOOTSTRAP_PREFIX/bin" \
    libdir="$BOOTSTRAP_PREFIX/lib" \
    libsubdir="$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION" \
    local_prefix="$BOOTSTRAP_PREFIX" \
    includedir="$BOOTSTRAP_PREFIX/include" \
    gcc_tooldir="$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET" \
    tooldir="$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET" \
    assertdir="$BOOTSTRAP_PREFIX/$BOOTSTRAP_TARGET/include" \
    infodir="$BOOTSTRAP_PREFIX/info" \
    mandir="$BOOTSTRAP_PREFIX/man" \
    man1dir="$BOOTSTRAP_PREFIX/man/man1"

/bin/cp "$BOOTSTRAP_SPECSFILE" \
    "$BOOTSTRAP_PREFIX/lib/gcc-lib/$BOOTSTRAP_TARGET/$BOOTSTRAP_VERSION/specs"

PATH="$BOOTSTRAP_PREFIX/bin:/usr/local/bin:/bin:/usr/bin"
CC="$BOOTSTRAP_PREFIX/bin/gcc"
CXX="$BOOTSTRAP_PREFIX/bin/g++"
export PATH CC CXX

cd "$GCC3_SRC"
patch -p1 < "$PATCHFILE"
sed 's/#inst\.\$\$#/inst.\$\$/g' install-sh > install-sh.new
mv install-sh.new install-sh

test -d "$BUILD_SUBDIR" || mkdir "$BUILD_SUBDIR"
cd "$BUILD_SUBDIR"

"$CONFIG_SHELL" ../configure --build="$HOST_ALIAS" --host="$HOST_ALIAS" --prefix="$FINAL_PREFIX" --enable-languages=c,c++,objc --disable-shared
/bin/gnumake CFLAGS="$GCC3_CFLAGS" all-gcc

test -d "$DESTDIR/usr" || mkdir "$DESTDIR/usr"
test -d "$DESTDIR/usr/local" || mkdir "$DESTDIR/usr/local"
test -d "$STAGE_PREFIX" || mkdir "$STAGE_PREFIX"
test -d "$STAGE_PREFIX/bin" || mkdir "$STAGE_PREFIX/bin"
test -d "$STAGE_PREFIX/include" || mkdir "$STAGE_PREFIX/include"
test -d "$STAGE_PREFIX/info" || mkdir "$STAGE_PREFIX/info"
test -d "$STAGE_PREFIX/lib" || mkdir "$STAGE_PREFIX/lib"
test -d "$STAGE_PREFIX/lib/gcc-lib" || mkdir "$STAGE_PREFIX/lib/gcc-lib"
test -d "$STAGE_PREFIX/lib/gcc-lib/$TARGET" || mkdir "$STAGE_PREFIX/lib/gcc-lib/$TARGET"
test -d "$STAGE_PREFIX/lib/gcc-lib/$TARGET/$VERSION" || mkdir "$STAGE_PREFIX/lib/gcc-lib/$TARGET/$VERSION"
test -d "$STAGE_PREFIX/man" || mkdir "$STAGE_PREFIX/man"
test -d "$STAGE_PREFIX/man/man1" || mkdir "$STAGE_PREFIX/man/man1"
test -d "$STAGE_PREFIX/man/man7" || mkdir "$STAGE_PREFIX/man/man7"
test -d "$STAGE_PREFIX/$TARGET" || mkdir "$STAGE_PREFIX/$TARGET"
test -d "$STAGE_PREFIX/$TARGET/bin" || mkdir "$STAGE_PREFIX/$TARGET/bin"
test -d "$STAGE_PREFIX/$TARGET/include" || mkdir "$STAGE_PREFIX/$TARGET/include"

/bin/gnumake CFLAGS="$GCC3_CFLAGS" install-gcc \
    prefix="$STAGE_PREFIX" \
    exec_prefix="$STAGE_PREFIX" \
    bindir="$STAGE_PREFIX/bin" \
    libdir="$STAGE_PREFIX/lib" \
    libsubdir="$STAGE_PREFIX/lib/gcc-lib/$TARGET/$VERSION" \
    local_prefix="$STAGE_PREFIX" \
    includedir="$STAGE_PREFIX/include" \
    gcc_tooldir="$STAGE_PREFIX/$TARGET" \
    tooldir="$STAGE_PREFIX/$TARGET" \
    assertdir="$STAGE_PREFIX/$TARGET/include" \
    infodir="$STAGE_PREFIX/info" \
    mandir="$STAGE_PREFIX/man" \
    man1dir="$STAGE_PREFIX/man/man1"

/bin/cp "$SPECSFILE" "$SPECS_DIR/specs"
