#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:$PATH
export DESTDIR VERSION PATH
. "$PKG_BUILD_HELPERS"

PATCHFILE="wget-$VERSION-openstep.patch"

patch -p1 < "$PATCHFILE"
run_configure --disable-nls --without-ssl --prefix=/usr/local
gnumake
gnumake install DESTDIR="$DESTDIR"
