#!/bin/sh

set -e

WGET="$ROOT_DIR/usr/local/bin/wget"

[ -x "$WGET" ]
output=`"$WGET" --version 2>&1`

case "$output" in
    "GNU Wget $PKG_VERSION"*)
        ;;
    *)
        exit 1
        ;;
esac
