#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin
CC=/bin/cc
CFLAGS="$PKG_SYSCC_ARCH_FLAGS "'-O2 -D_POSIX_SOURCE'
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
export PATH CC CFLAGS GREP EGREP
. "$PKG_BUILD_HELPERS"
patch -p1 < "mktemp-$VERSION-openstep.patch"
run_configure --prefix=/usr/local
/bin/gnumake
/bin/gnumake install DESTDIR="$DESTDIR"
