#!/bin/sh
set -e
DESTDIR=$1
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC=/usr/local/bin/gcc-4.2
CFLAGS='-O2 -march=i486 -DNeXT'
AWK=/usr/local/bin/gawk
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
CHARSET=ASCII
export PATH CC CFLAGS AWK GREP EGREP CHARSET
if test -d "libgpg-error-$2"; then cd "libgpg-error-$2"; fi
patch -p1 < "libgpg-error-$2-openstep.patch"
. "$PKG_BUILD_HELPERS"
run_configure --build=$PKG_TARGET --prefix=/usr/local \
    --disable-nls --disable-shared --enable-static --disable-dependency-tracking
/bin/gnumake SHELL="$CONFIG_SHELL"
/bin/gnumake SHELL="$CONFIG_SHELL" check
/bin/gnumake SHELL="$CONFIG_SHELL" install DESTDIR="$DESTDIR"
/bin/ranlib "$DESTDIR/usr/local/lib/libgpg-error.a"
