#!/bin/sh
set -e
TMP=/usr/tmp/gpg-error-test.$$
trap '/bin/rm -f "$TMP" "$TMP.c"' 0
trap 'exit 1' 1 2 15
cat > "$TMP.c" <<'EOF'
#include <gpg-error.h>
#include <assert.h>
#include <errno.h>
#include <string.h>
int main(void)
{
    char text[128], small[2] = {'x', 'y'};
    gpg_error_t err = gpg_err_make(GPG_ERR_SOURCE_GCRYPT, GPG_ERR_INV_VALUE);
    assert(gpg_error_check_version(GPG_ERROR_VERSION));
    assert(gpg_err_source(err) == GPG_ERR_SOURCE_GCRYPT);
    assert(gpg_err_code(err) == GPG_ERR_INV_VALUE);
    assert(gpg_strerror_r(err, text, sizeof text) == 0);
    assert(!strcmp(text, gpg_strerror(err)));
    assert(gpg_strerror_r(err, small, sizeof small) == ERANGE);
    assert(small[1] == 0);
    assert(gpg_err_code_to_errno(gpg_err_code_from_errno(ENOENT)) == ENOENT);
    assert(gpg_strerror_r(gpg_error_from_errno(ENOENT), text, sizeof text) == 0);
    assert(text[0]);
    return 0;
}
EOF
/usr/local/bin/gcc-4.2 -O2 ${PKG_GCC42_ARCH_FLAGS-} -DNeXT -I"$LOCAL_ROOT/include" \
    "$TMP.c" -L"$LOCAL_ROOT/lib" -lgpg-error -o "$TMP"
"$TMP"
"$LOCAL_ROOT/bin/gpg-error" --version
echo 'libgpg-error installed headers, error mapping and bounded messages passed'
