#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
PREFIX=/usr/local
PATCHFILE="quickjs-$VERSION-openstep.patch"
CC=/usr/local/bin/gcc-4.2
AR=/bin/ar
RANLIB=/bin/ranlib
QJS_VERSION=`cat VERSION`
OBJDIR=.obj
CFLAGS="$PKG_GCC42_ARCH_FLAGS "'-pipe -O2 -std=gnu9x -Wall -D_GNU_SOURCE -DNeXT -D__ARCHITECTURE__="'"$PKG_ARCH"'" -I. -I/NextDeveloper/Headers -I/NextDeveloper/Headers/bsd'
LIBS="-lm"

export DESTDIR VERSION PATH PREFIX CC AR RANLIB QJS_VERSION OBJDIR CFLAGS LIBS

if [ -f "$PATCHFILE" ]; then
    patch -p1 < "$PATCHFILE"
fi

rm -f qjs qjsc repl.c libquickjs.a
rm -f "$OBJDIR"/*.o
test -d "$OBJDIR" || mkdir "$OBJDIR"

"$CC" $CFLAGS -c quickjs.c -o "$OBJDIR/quickjs.o"
"$CC" $CFLAGS -c dtoa.c -o "$OBJDIR/dtoa.o"
"$CC" $CFLAGS -c libregexp.c -o "$OBJDIR/libregexp.o"
"$CC" $CFLAGS -c libunicode.c -o "$OBJDIR/libunicode.o"
"$CC" $CFLAGS -c cutils.c -o "$OBJDIR/cutils.o"
"$CC" $CFLAGS -c quickjs-libc.c -o "$OBJDIR/quickjs-libc.o"

"$AR" cr libquickjs.a \
    "$OBJDIR/quickjs.o" "$OBJDIR/dtoa.o" "$OBJDIR/libregexp.o" \
    "$OBJDIR/libunicode.o" "$OBJDIR/cutils.o" "$OBJDIR/quickjs-libc.o"
"$RANLIB" libquickjs.a

"$CC" $CFLAGS -c qjsc.c -o "$OBJDIR/qjsc.o"
"$CC" -o qjsc "$OBJDIR/qjsc.o" libquickjs.a $LIBS

./qjsc -s -c -o repl.c -m repl.js
"$CC" $CFLAGS -c repl.c -o "$OBJDIR/repl.o"
"$CC" $CFLAGS -c qjs.c -o "$OBJDIR/qjs.o"
"$CC" -o qjs "$OBJDIR/qjs.o" "$OBJDIR/repl.o" libquickjs.a $LIBS

test -d "$DESTDIR/usr" || mkdir "$DESTDIR/usr"
test -d "$DESTDIR/usr/local" || mkdir "$DESTDIR/usr/local"
test -d "$DESTDIR/usr/local/bin" || mkdir "$DESTDIR/usr/local/bin"
test -d "$DESTDIR/usr/local/lib" || mkdir "$DESTDIR/usr/local/lib"
test -d "$DESTDIR/usr/local/lib/quickjs" || mkdir "$DESTDIR/usr/local/lib/quickjs"
test -d "$DESTDIR/usr/local/include" || mkdir "$DESTDIR/usr/local/include"
test -d "$DESTDIR/usr/local/include/quickjs" || mkdir "$DESTDIR/usr/local/include/quickjs"

cp qjs "$DESTDIR/usr/local/bin/qjs"
cp qjsc "$DESTDIR/usr/local/bin/qjsc"
cp libquickjs.a "$DESTDIR/usr/local/lib/quickjs/libquickjs.a"
cp quickjs.h "$DESTDIR/usr/local/include/quickjs/quickjs.h"
cp quickjs-libc.h "$DESTDIR/usr/local/include/quickjs/quickjs-libc.h"
cp stdint.h "$DESTDIR/usr/local/include/quickjs/stdint.h"
