#!/bin/sh

set -e

PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
export PATH

cat > conftest.c <<'EOF'
#include <ft2build.h>
#include FT_FREETYPE_H

int
main(void)
{
    FT_Library library;

    if (FT_Init_FreeType(&library))
        return 1;
    FT_Done_FreeType(library);
    return 0;
}
EOF

/bin/cc `/usr/local/bin/freetype-config --cflags` -o conftest conftest.c `/usr/local/bin/freetype-config --libs --static`
./conftest
rm -f conftest conftest.c
