#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin
CC=/usr/local/bin/gcc-4.2
CFLAGS="$PKG_GCC42_ARCH_FLAGS "'-O2 -DNeXT -D_POSIX_SOURCE'
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
AWK=/usr/local/bin/gawk
export PATH CC CFLAGS GREP EGREP AWK
. "$PKG_BUILD_HELPERS"

# OPENSTEP's SPARC libc compares bytes as signed in memcmp() and strcmp(); see
# pkg_cmp_shim in build-helpers.sh.  Empty on x86.  It is forced in at make
# time only: configure's own tests do not cope with it.
CMPFLAGS=`pkg_cmp_shim "\`pwd\`/openstep-cmp"`
patch -p1 < "findutils-$VERSION-openstep.patch"
run_configure --prefix=/usr/local --disable-nls --disable-dependency-tracking
/bin/gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS"
/bin/gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS" install DESTDIR="$DESTDIR"
