#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin
CC=/usr/local/bin/gcc-4.2
CFLAGS="$PKG_GCC42_ARCH_FLAGS "'-O2 -DNeXT -D_POSIX_SOURCE'
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
AWK=/usr/local/bin/gawk
export PATH CC CFLAGS GREP EGREP AWK
. "$PKG_BUILD_HELPERS"

# OPENSTEP's SPARC libc compares bytes as signed in memcmp() and strcmp(); see
# pkg_cmp_obj in build-helpers.sh.  The gnulib wrappers here cannot be preceded
# by a forced -include (pkg_cmp_shim): its <string.h> would pick up gnulib's own
# string.h before config.h has defined "restrict".  So link unsigned definitions
# in instead.  Empty on x86.  Used at make time only.
CMPOBJ=`pkg_cmp_obj "\`pwd\`/openstep-cmp"`
patch -p1 < "findutils-$VERSION-openstep.patch"
run_configure --prefix=/usr/local --disable-nls --disable-dependency-tracking
/bin/gnumake LDFLAGS="$LDFLAGS $CMPOBJ"
/bin/gnumake LDFLAGS="$LDFLAGS $CMPOBJ" install DESTDIR="$DESTDIR"
