#!/bin/sh

set -e

DESTDIR=$1

PATH=/usr/ucb:/bin:/usr/bin:/usr/local/bin:$PATH
CC=/bin/cc
export PATH CC

if [ -d BusMasterIDE-a171a1d ]; then
    cd BusMasterIDE-a171a1d
fi

/bin/make CC=/bin/cc

if [ ! -d BusMasterIDE.config ]; then
    echo "BusMasterIDE.config was not built." >&2
    exit 1
fi

test -d "$DESTDIR/usr" || mkdir "$DESTDIR/usr"
test -d "$DESTDIR/usr/local" || mkdir "$DESTDIR/usr/local"
test -d "$DESTDIR/usr/local/Devices" || mkdir "$DESTDIR/usr/local/Devices"
test -d "$DESTDIR/usr/local/Devices/BusMasterIDE.config" || mkdir "$DESTDIR/usr/local/Devices/BusMasterIDE.config"

(
    cd BusMasterIDE.config
    tar cf - .
) | (
    cd "$DESTDIR/usr/local/Devices/BusMasterIDE.config"
    tar xpf -
)
