#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC=/bin/cc
GREP=/bin/grep
EGREP=/usr/bin/egrep
PATCHFILE="gawk-$VERSION-openstep.patch"

export DESTDIR VERSION PATH CC GREP EGREP
. "$PKG_BUILD_HELPERS"

if [ -f "$PATCHFILE" ]; then
    patch -p1 < "$PATCHFILE"
fi

ac_cv_func_working_mktime=yes
export ac_cv_func_working_mktime
run_configure --disable-nls --prefix=/usr/local
gnumake
gnumake install DESTDIR="$DESTDIR"
