#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC="/bin/cc $PKG_SYSCC_ARCH_FLAGS"
GREP=/bin/grep
EGREP=/usr/bin/egrep
PATCHFILE="gawk-$VERSION-openstep.patch"

export DESTDIR VERSION PATH CC GREP EGREP
. "$PKG_BUILD_HELPERS"

# OPENSTEP's SPARC libc compares bytes as signed in memcmp() and strcmp(); see
# pkg_cmp_shim in build-helpers.sh.  Empty on x86.  It is forced in at make
# time only: configure's own tests do not cope with it.
CMPFLAGS=`pkg_cmp_shim "\`pwd\`/openstep-cmp"`

if [ -f "$PATCHFILE" ]; then
    patch -p1 < "$PATCHFILE"
fi

ac_cv_func_working_mktime=yes
export ac_cv_func_working_mktime
run_configure --disable-nls --prefix=/usr/local
gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS"
gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS" install DESTDIR="$DESTDIR"
