#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:$PATH
export DESTDIR VERSION PATH
. "$PKG_BUILD_HELPERS"

PATCHFILE="make-$VERSION-openstep.patch"

patch -p1 < "$PATCHFILE"
run_configure --prefix=/usr/local
gnumake
gnumake install DESTDIR="$DESTDIR"

cd "$DESTDIR/usr/local/bin"
rm -f gnumake
mv make gnumake
