#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:$PATH
# gcc42 needs this make to build, so make is built with the system compiler.
# PKG_MAKE_CC overrides it (for example "/usr/local/bin/gcc-4.2 -march=i486").
CC=${PKG_MAKE_CC-"/bin/cc $PKG_SYSCC_ARCH_FLAGS"}
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
AWK=/usr/local/bin/gawk
export DESTDIR VERSION PATH CC GREP EGREP AWK
. "$PKG_BUILD_HELPERS"

PATCHFILE="make-$VERSION-openstep.patch"

patch -p1 < "$PATCHFILE"
run_configure --prefix=/usr/local --disable-nls --disable-dependency-tracking
/bin/gnumake SHELL="$CONFIG_SHELL"
/bin/gnumake SHELL="$CONFIG_SHELL" install DESTDIR="$DESTDIR"

cd "$DESTDIR/usr/local/bin"
rm -f gnumake
mv make gnumake
