#!/bin/sh

set -e

TMP=/usr/tmp/libpng-test.$$

cat > "$TMP.c" <<'EOF'
#include <png.h>

int main(void)
{
    png_structp png_ptr;
    png_infop info_ptr;

    png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, 0, 0, 0);
    if (png_ptr == 0)
        return 1;

    info_ptr = png_create_info_struct(png_ptr);
    if (info_ptr == 0) {
        png_destroy_read_struct(&png_ptr, 0, 0);
        return 2;
    }

    png_destroy_read_struct(&png_ptr, &info_ptr, 0);
    return 0;
}
EOF

/bin/cc -DNeXT -I"$LOCAL_ROOT/include" "$TMP.c" \
    "$LOCAL_ROOT/lib/libpng16.a" -lz -lm -o "$TMP"

"$TMP"

rm -f "$TMP.c" "$TMP"
