#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/bin:/usr/bin:/usr/local/bin:$PATH
CC="/bin/cc $PKG_SYSCC_ARCH_FLAGS"
PATCHFILE="coreutils-$VERSION-openstep.patch"
CPPFLAGS='-DMOUNTED=\"/etc/mtab\"'

export DESTDIR VERSION PATH CC PATCHFILE CPPFLAGS
. "$PKG_BUILD_HELPERS"

# OPENSTEP's SPARC libc compares bytes as signed in memcmp() and strcmp(); see
# pkg_cmp_shim in build-helpers.sh.  Empty on x86.  It is forced in at make
# time only: configure's own tests do not cope with it.
CMPFLAGS=`pkg_cmp_shim "\`pwd\`/openstep-cmp"`

patch -p1 < "$PATCHFILE"
run_configure --build=$PKG_TARGET --host=$PKG_TARGET \
  --disable-nls --prefix=/usr/local
gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS"
gnumake CPPFLAGS="$CPPFLAGS $CMPFLAGS" install DESTDIR="$DESTDIR"
