#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC=/bin/cc
GREP=/bin/grep
EGREP=/usr/bin/egrep
AWK=/usr/local/bin/gawk
M4=/usr/local/bin/m4
SED=/bin/sed
lt_cv_path_SED=/bin/sed
PATCHFILE="flex-$VERSION-openstep.patch"

export DESTDIR VERSION PATH CC GREP EGREP AWK M4 SED lt_cv_path_SED
. "$PKG_BUILD_HELPERS"

patch -p1 < "$PATCHFILE"
run_configure --disable-nls --prefix=/usr/local
gnumake
touch doc/flex.1
gnumake install DESTDIR="$DESTDIR"
