#!/bin/sh
set -e
DESTDIR=$1
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC=/usr/local/bin/gcc-4.2
CFLAGS='-O2 -march=i486 -DNeXT'
AWK=/usr/local/bin/gawk
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
CHARSET=ASCII
export PATH CC CFLAGS AWK GREP EGREP CHARSET
if test -d "fribidi-$2"; then cd "fribidi-$2"; fi
patch -p1 < "fribidi-$2-openstep.patch"
. "$PKG_BUILD_HELPERS"
run_configure --build=$PKG_TARGET --prefix=/usr/local \
    --disable-shared --enable-static --disable-dependency-tracking
# Avoid collisions when libtool extracts the convenience archive with NeXT ar.
for suffix in '' -cap-rtl -cp1255 -cp1256 -iso8859-6 -iso8859-8 -utf8
do
    /bin/rm -f "charset/cs$suffix.c"
    /bin/ln -s "fribidi-char-sets$suffix.c" "charset/cs$suffix.c"
done
sed 's/fribidi-char-sets\([-a-z0-9]*\)\.lo/cs\1.lo/g' charset/Makefile > charset/Makefile.tmp
/bin/mv charset/Makefile.tmp charset/Makefile
/bin/rm -f charset/.libs/libfribidi-char-sets.a charset/libfribidi-char-sets.la
/bin/gnumake SHELL="$CONFIG_SHELL"
/bin/gnumake SHELL="$CONFIG_SHELL" LOG_COMPILER="$CONFIG_SHELL" check
/bin/gnumake SHELL="$CONFIG_SHELL" install DESTDIR="$DESTDIR"
/bin/ranlib "$DESTDIR/usr/local/lib/libfribidi.a"
