#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PREFIX=/usr/local
PATCHFILE="nsgenbind-$VERSION-openstep.patch"
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
NSSHARED=/usr/local/share/netsurf-buildsystem
CC=/usr/local/bin/gcc
BUILD_CC=/usr/local/bin/gcc
MAKE=gnumake
CCACHE=
CC_CAN_BUILD_AND_DEP=no
CC_CANNOT_DEP=yes
GCCVER=2
BUILDDIR=build-openstep
CFLAGS=-DNeXT

export DESTDIR VERSION PREFIX PATH NSSHARED CC BUILD_CC MAKE
export CCACHE CC_CAN_BUILD_AND_DEP CC_CANNOT_DEP GCCVER BUILDDIR CFLAGS

if [ -d "nsgenbind-$VERSION" ]; then
    cd "nsgenbind-$VERSION"
fi

patch -p1 < "$PATCHFILE"

gnumake Q= PREFIX="$PREFIX" NSSHARED="$NSSHARED" GCCVER=2 WARNFLAGS=

test -d "$DESTDIR/usr" || mkdir "$DESTDIR/usr"
test -d "$DESTDIR/usr/local" || mkdir "$DESTDIR/usr/local"
test -d "$DESTDIR/usr/local/bin" || mkdir "$DESTDIR/usr/local/bin"

cp "$BUILDDIR/nsgenbind" "$DESTDIR$PREFIX/bin/nsgenbind"
chmod 755 "$DESTDIR$PREFIX/bin/nsgenbind"
