#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC=/bin/cc
AWK=/usr/local/bin/gawk
CPPFLAGS=-I/usr/local/include
LDFLAGS=-L/usr/local/lib
PATCHFILE="openssh-$VERSION-openstep.patch"

export DESTDIR VERSION PATH CC AWK CPPFLAGS LDFLAGS
. "$PKG_BUILD_HELPERS"

patch -p1 < "$PATCHFILE"
run_configure \
  --build=i386-next-openstep4 \
  --host=i386-next-openstep4 \
  --prefix=/usr/local \
  --with-ssl-dir=/usr/local \
  --with-zlib=/usr/local

gnumake
gnumake install-nokeys DESTDIR="$DESTDIR"
