#!/bin/sh

set -e

DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
# OpenSSH 8.x and later insist on C99 (variadic macros), which the system cc
# (gcc 2.x) lacks, so build with gcc 4.2.  On SPARC gcc 4.2 miscompiles at -O2
# and above in some programs; PKG_SSH_OPT overrides (try -O1 or -O0 on SPARC if
# ssh or sshd misbehave).
CC="/usr/local/bin/gcc-4.2 $PKG_GCC42_ARCH_FLAGS"
CFLAGS="${PKG_SSH_OPT--O2}"
AWK=/usr/local/bin/gawk
CPPFLAGS=-I/usr/local/include
LDFLAGS=-L/usr/local/lib
PATCHFILE="openssh-$VERSION-openstep.patch"

export DESTDIR VERSION PATH CC CFLAGS AWK CPPFLAGS LDFLAGS
. "$PKG_BUILD_HELPERS"

patch -p1 < "$PATCHFILE"
run_configure \
  --build=$PKG_TARGET \
  --host=$PKG_TARGET \
  --prefix=/usr/local \
  --with-ssl-dir=/usr/local \
  --with-zlib=/usr/local

gnumake
gnumake install-nokeys DESTDIR="$DESTDIR"

# The boot-time script, its default settings and the README.
/usr/local/bin/mkdir -p "$DESTDIR/usr/local/etc" "$DESTDIR/usr/local/share/openssh"
/bin/cp pkg-files/rc.sshd "$DESTDIR/usr/local/etc/rc.sshd"
/bin/cp pkg-files/rc.sshd.conf.dist "$DESTDIR/usr/local/etc/rc.sshd.conf.dist"
/bin/cp pkg-files/README "$DESTDIR/usr/local/share/openssh/README"
/bin/chmod 755 "$DESTDIR/usr/local/etc/rc.sshd"
