#!/bin/sh
set -e
DESTDIR=$1
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CC=/usr/local/bin/gcc-4.2
CFLAGS='-O2 '"$PKG_GCC42_ARCH_FLAGS"' -DNeXT'
AWK=/usr/local/bin/gawk
GREP=/usr/local/bin/grep
EGREP='/usr/local/bin/grep -E'
export PATH CC CFLAGS AWK GREP EGREP
. "$PKG_BUILD_HELPERS"
run_configure --build=$PKG_TARGET --prefix=/usr/local \
    --disable-shared --enable-static --disable-dependency-tracking
/bin/gnumake SHELL="$CONFIG_SHELL"
/bin/gnumake SHELL="$CONFIG_SHELL" install DESTDIR="$DESTDIR"
/bin/ranlib "$DESTDIR/usr/local/lib/libmad.a"
