#!/bin/sh

set -e

CURL="$ROOT_DIR/usr/local/bin/curl"
TMPFILE=/tmp/pkg-curl-$$.txt

[ -x "$CURL" ]

version_output=`"$CURL" -V`
case "$version_output" in
    *zlib*)
        :
    ;;
    *)
        echo "curl is missing zlib support" >&2
        exit 1
    ;;
esac

/bin/rm -f "$TMPFILE"
/bin/echo hello > "$TMPFILE"

value=`"$CURL" -fsS "file://$TMPFILE"`
[ "$value" = hello ]

/bin/rm -f "$TMPFILE"
