#!/bin/sh
set -e
DESTDIR=$1
VERSION=$2
PATH=/usr/local/bin:/usr/ucb:/bin:/usr/bin:$PATH
CONFIG_SHELL=/usr/local/bin/ksh
export PATH CONFIG_SHELL
if test -d "ffmpeg-$VERSION"; then cd "ffmpeg-$VERSION"; fi
patch -p1 < "ffmpeg-$VERSION-openstep.patch"

# FFmpeg's configure is not Autoconf and does not accept run_configure's
# CONFIG_SHELL argument. Invoke the installed shell explicitly.
"$CONFIG_SHELL" ./configure --cc=/usr/local/bin/gcc-4.2 \
    --prefix=/usr/local --target-os=openstep --arch=x86 \
    --extra-cflags="-O2 -fno-builtin-memset $PKG_GCC42_ARCH_FLAGS -DNeXT -I/usr/local/include ${CFLAGS-}" \
    --extra-ldflags=-L/usr/local/lib --enable-static --disable-shared \
    --disable-ffplay --disable-ffserver --disable-devices --disable-vhook \
    --disable-mmx --disable-yasm \
    --enable-gpl --enable-swscale --enable-postproc

# The upstream makefiles use eval, which the stock gnumake 3.74 lacks.
/usr/local/bin/gnumake SHELL="$CONFIG_SHELL"
/usr/local/bin/gcc-4.2 -O2 -fno-builtin-memset $PKG_GCC42_ARCH_FLAGS -std=gnu99 -DNeXT ${CFLAGS-} -I. -Ilibavutil -I/usr/local/include \
    tests/openstep.c libavutil/openstep.c -L/usr/local/lib \
    -lcurl -lssl -lcrypto -lz -lm -o openstep-test
./openstep-test
/usr/local/bin/gnumake SHELL="$CONFIG_SHELL" install DESTDIR="$DESTDIR"
for lib in avcodec avformat avutil avdevice swscale postproc
do
    /bin/ranlib "$DESTDIR/usr/local/lib/lib$lib.a"
done
DOCDIR=$DESTDIR/usr/local/share/doc/ffmpeg
/usr/local/bin/mkdir -p "$DOCDIR"
for file in README COPYING.GPLv2 COPYING.LGPLv2.1
do
    /usr/bin/install -c -m 644 "$file" "$DOCDIR/$file"
done
